Update .zshrc

diff --git a/dot_zshrc.tmpl b/dot_zshrc.tmpl
--- a/dot_zshrc.tmpl
+++ b/dot_zshrc.tmpl
@@ -32,11 +32,27 @@ source ~/.local/share/omarchy/default/bash/envs
 source ~/.local/share/omarchy/default/bash/envs
 source ~/.local/share/omarchy/default/bash/functions
 {{ end }}
-#### BEGIN HOME PROFILE ####
+#### END HOME PROFILE ####
 {{ end }}
 
+
 {{ if eq .profile "work"}}
-#### END WORK PROFILE ####
+#### BEGIN WORK PROFILE ####
+alias ls='eza -lh --group-directories-first --icons=auto'
+alias lsa='ls -a'
+alias lt='eza --tree --level=2 --long --icons --git'
+alias lta='lt -a'
+alias ff="fzf --preview 'bat --style=numbers --color=always {}'"
+alias cd="zd"
+zd() {
+  if [ $# -eq 0 ]; then
+    builtin cd ~ && return
+  elif [ -d "$1" ]; then
+    builtin cd "$1"
+  else
+    z "$@" && printf " \U000F17A9 " && pwd || echo "Error: Directory not found"
+  fi
+}
 export AMP_API_KEY={{ onepasswordRead "op://Employee/Amp API Key/credential" }}
 export SRC_ACCESS_TOKEN={{ onepasswordRead "op://Employee/demo.sourcegraph.com API Token/password" }}
 export SRC_ENDPOINT={{ onepasswordRead "op://Employee/demo.sourcegraph.com API Token/website" }}
